name: A©tor Engine
on: [push, workflow_dispatch]
permissions: {contents: write, pages: write, id-token: write}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x ./scripts/generate_wrappers.sh && ./scripts/generate_wrappers.sh
      - uses: actions/upload-pages-artifact@v3
        with: {path: '.'}
      - uses: actions/deploy-pages@v4
